### ISSUE TITLE
Error while flashing Custom ROM

### ISSUE THREAD

**Issue by heretohelporbehelped** [Blacksuan19/android_device_xiaomi_phoenix#3]
In TWRP I was not able to see System and Vendor Partitions in Wipe Section so like a fool 
I flashed twrp image in Super, this put me in bootloop
After this I flashed some files from the fastboot version of Stock ROM in the following manner
https://www.droidwin.com/unbrick-poco-x2-fastboot-commands/

But even after this I am was in Bootloop so to see if it is a TWRP problem due to which I was not able to see System and Vendor Partitions, I installed Orange Fox Recovery.

After installing Orange Fox Recovery R11
I wiped Dalvik / ART Cache
             Data
             Cache
             
And flashed the Custom ROM(Evolution X 5.8) but then this happens :            

assert failed: update_dynamic_partitions (package_extract_file("dynamic_partitions_op_list"))
Updater Process ended with EROOR :1
Error installing ZIP file "path of the file"

Please help !!!

**Comment by heretohelporbehelped** [comment]
@SreekanthPalakurthi please help

**Comment by Blacksuan19** [comment]
Can you not

**Comment by Blacksuan19** [comment]
Ask in device telegram group
